package com.proj.automation.plugin

import java.security.MessageDigest

/**
 * `PACKAGE.lock`: every other file's SHA-256 and the vendored library versions. Generated by the
 * build tool; verified at install. Its own SHA-256 is the **package hash** the owner approves:
 * because it covers every file, it identifies everything that will run.
 *
 * Format (one entry per line, sorted, so the same content always gives the same hash):
 * ```
 * agp-lock 1
 * file <sha256> <path>
 * library <id> <version>
 * ```
 */
data class PackageLock(val files: Map<String, String>, val libraries: Map<String, String>) {

    fun render(): String = buildString {
        append("$HEADER\n")
        files.toSortedMap().forEach { (path, hash) -> append("file $hash $path\n") }
        libraries.toSortedMap().forEach { (id, version) -> append("library $id $version\n") }
    }

    companion object {
        const val FILE = "PACKAGE.lock"
        private const val HEADER = "agp-lock 1"

        fun sha256(bytes: ByteArray): String =
            MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }

        fun forFiles(entries: Map<String, ByteArray>, libraries: Map<String, String>) =
            PackageLock(entries.filterKeys { it != FILE && it != PackageSignature.FILE }.mapValues { sha256(it.value) }, libraries)

        fun parse(text: String): PackageLock {
            val lines = text.lines().filter { it.isNotBlank() }
            if (lines.firstOrNull() != HEADER) throw PluginPackageException("$FILE: unsupported format")
            val files = mutableMapOf<String, String>()
            val libraries = mutableMapOf<String, String>()
            for (line in lines.drop(1)) {
                val parts = line.split(' ', limit = 3)
                when {
                    parts.size == 3 && parts[0] == "file" && parts[1].matches(Regex("[0-9a-f]{64}")) -> files[parts[2]] = parts[1]
                    parts.size == 3 && parts[0] == "library" -> libraries[parts[1]] = parts[2]
                    else -> throw PluginPackageException("$FILE: invalid line '$line'")
                }
            }
            return PackageLock(files, libraries)
        }

        /** Checks that the lock lists exactly the package's files with matching hashes. Returns the package hash. */
        fun verify(files: PackageFiles): Pair<PackageLock, String> {
            val text = files.text(FILE) ?: throw PluginPackageException("Missing $FILE; build packages with the agp tool")
            val lock = parse(text)
            // the signature covers the lock's hash, so it is the one file the lock does not list
            val actual = files.entries.keys - FILE - PackageSignature.FILE
            val missing = lock.files.keys - actual
            val extra = actual - lock.files.keys
            if (missing.isNotEmpty()) throw PluginPackageException("$FILE lists files that are not in the package: $missing")
            if (extra.isNotEmpty()) throw PluginPackageException("Files not listed in $FILE: $extra")
            lock.files.forEach { (path, hash) ->
                if (sha256(files.entries.getValue(path)) != hash) throw PluginPackageException("'$path' does not match its hash in $FILE")
            }
            return lock to sha256(text.toByteArray())
        }
    }
}
